name: jaxnets

channels:
  - default
  - conda-forge

dependencies:
  - python>=3.12
  - ipython
  - ipykernel
  - pre-commit

  - numpy
  - optax
  - equinox
  - pandas>=2.0
  - pytables
  - submitit
  - matplotlib
  - ipdb

  - pytorch::pytorch
  - conda-forge::jax

  - pip
  - pip:
      - -e .